spring.application.name=spring-demo-mcp


spring.datasource.url=jdbc:h2:file:./data/loandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

##Using together AI key
spring.ai.openai.base-url=https://api.together.xyz
spring.ai.openai.api-key=Your key
spring.ai.openai.chat.options.model=Qwen/Qwen2.5-7B-Instruct-Turbo
spring.ai.openai.chat.options.temperature=0.2

##Enable http transport for spring mcp seerver
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

# Optional: Server operating mode (SYNC or ASYNC)
spring.ai.mcp.server.type=SYNC

logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.ai=DEBUG
